sohotz/Hippy

framework/ohos/src/main/ets/renderer_native/HippyComponentFactory.ets, framework/ohos/src/main/ets/renderer_native/components/HippyModalView.ets
=> feat(ohos): add modal component

framework/ohos/src/main/ets/renderer_native/HippyRenderView.ets, framework/ohos/src/main/ets/renderer_native/components/HippyRenderRegisterMap.ets, framework/ohos/src/main/ets/renderer_native/components/image/HRImageView.ets, framework/ohos/src/main/ets/renderer_native/components/list/HRListItemView.ets, framework/ohos/src/main/ets/renderer_native/components/list/HRListView.ets, framework/ohos/src/main/ets/renderer_native/components/pager/HRViewPager.ets, framework/ohos/src/main/ets/renderer_native/components/pager/HRViewPagerItem.ets, framework/ohos/src/main/ets/renderer_native/components/pullfooter/HRPullFooter.ets, framework/ohos/src/main/ets/renderer_native/components/pullheader/HRPullHeader.ets, framework/ohos/src/main/ets/renderer_native/components/refreshwrapper/HRRefreshWrapper.ets, framework/ohos/src/main/ets/renderer_native/components/refreshwrapper/HRRefreshWrapperItem.ets, framework/ohos/src/main/ets/renderer_native/components/scroller/HRScrollContentView.ets, framework/ohos/src/main/ets/renderer_native/components/scroller/HRScrollView.ets, framework/ohos/src/main/ets/renderer_native/components/waterfall/HRWaterfall.ets, framework/ohos/src/main/ets/renderer_native/components/waterfall/HRWaterfallItem.ets, framework/ohos/src/main/ets/renderer_native/components/web/HRWebView.ets, framework/ohos/src/main/ets/renderer_native/uimanager/HRManager.ets
add waterfall, pager, pullfooter and pullheader, modify list,image and webview
=> add waterfall, pager, pullfooter and pullheader, modify list,image and webview

framework/ohos/src/main/ets/renderer_native/HippyRenderView.ets, framework/ohos/src/main/ets/renderer_native/components/HippyRenderRegisterMap.ets, framework/ohos/src/main/ets/renderer_native/components/textinput/HRTextInputView.ets, framework/ohos/src/main/ets/renderer_native/components/web/HRWebView.ets
=> complete webview/add textinput

framework/ohos/src/main/ets/renderer_native/components/modal/HRModalView.ets
Modify modal component adapt to ohos, adapte transparent attrbute and onShow onRequestClose events
=> Modify modal component adapt to ohos

framework/ohos/src/main/ets/renderer_native/components/list/HRListView.ets
=> modify list

framework/ohos/src/main/ets/renderer_native/components/image/HRImageView.ets
=> add image features

framework/ohos/src/main/ets/renderer_native/HippyRenderView.ets, framework/ohos/src/main/ets/renderer_native/components/richtext/HRRichTextView.ets
=> feat(ohos): Add Text Component Impl

framework/ohos/src/main/ets/hippy_framework/HippyEngineImpl.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/DefaultHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyResourceLoader.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HttpTaskCallbackImpl.ets, framework/ohos/src/main/ets/renderer_native/FrameworkProxy.ets, framework/ohos/src/main/ets/renderer_native/NativeRender.ets, framework/ohos/src/main/ets/renderer_native/NativeRenderImpl.ets, framework/ohos/src/main/ets/renderer_native/components/image/HRImageView.ets, framework/ohos/src/main/ets/renderer_native/components/image/ImageLoader.ets, framework/ohos/src/main/ets/renderer_native/components/image/ImageLoaderAdapter.ets, framework/ohos/src/main/ets/support/common/HippyTypes.ets, framework/ohos/src/main/ets/support/utils/UrlUtils.ets, framework/ohos/src/main/ets/vfs/DefaultProcessor.ets, framework/ohos/src/main/ets/vfs/Processor.ets, framework/ohos/src/main/ets/vfs/ProcessorCallback.ets, framework/ohos/src/main/ets/vfs/ResourceDataHolder.ets, framework/ohos/src/main/ets/vfs/VfsManager.ets
=> cmplete vfsmanager basic function

framework/ohos/src/main/ets/renderer_native/NativeRenderImpl.ets
=> feat(ohos): fix update virtual node before measure text

framework/examples/ohos-demo/src/main/ets/entryability/EntryAbility.ets, framework/examples/ohos-demo/src/main/ets/pages/Index.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/bridge/bundleloader/HippyAssetBundleLoader.ets, framework/ohos/src/main/ets/support/utils/TextUtils.ets
=> make getBundlePath work

framework/ohos/src/main/ets/hippy_framework/HippyEngine.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineContext.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineContextImpl.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/adapter/device/DefaultDeviceAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/DefaultHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpRequest.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyResourceLoader.ets, framework/ohos/src/main/ets/hippy_framework/adapter/monitor/DefaultEngineMonitorAdapter.ets, framework/ohos/src/main/ets/renderer_native/components/image/HRImageView.ets, framework/ohos/src/main/ets/renderer_native/components/image/ImageDataSupplier.ets, framework/ohos/src/main/ets/renderer_native/components/image/ImageLoader.ets, framework/ohos/src/main/ets/renderer_native/components/image/ImageRequestListener.ets, framework/ohos/src/main/ets/vfs/ResourceDataHolder.ets
=> make DefaultHttpAdapter work

framework/ohos/src/main/ets/renderer_native/components/richtext/HRRichTextView.ets
=> feat(ohos): Add text & text, text & image span

framework/ohos/src/main/ets/hippy_framework/HippyEngine.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineContext.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineContextImpl.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/storage/DefaultStorageAdapter.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridge.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeImpl.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManager.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/bridge/bundleloader/HippyAssetBundleLoader.ets, framework/ohos/src/main/ets/hippy_framework/bridge/bundleloader/HippyFileBundleLoader.ets, framework/ohos/src/main/ets/hippy_framework/connector/DomManager.ets, framework/ohos/src/main/ets/vfs/VfsManager.ets
=> feat(ohos): init engine && load module

framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc, modules/ohos/oh_napi/include/oh_napi/oh_measure_text.h, modules/ohos/oh_napi/src/oh_measure_text.cc
=> feat(ohos): use c measure direct

framework/ohos/src/main/ets/renderer_native/components/base/HippyRenderBaseView.ets
=> feat(ohos): keep size of imageSpan and collect padding

framework/ohos/src/main/ets/renderer_native/components/list/HRListItemView.ets, framework/ohos/src/main/ets/renderer_native/components/list/HRListView.ets, framework/ohos/src/main/ets/renderer_native/components/pullfooter/HRPullFooter.ets, framework/ohos/src/main/ets/renderer_native/components/pullheader/HRPullHeader.ets, framework/ohos/src/main/ets/renderer_native/components/textinput/HRTextInputView.ets, framework/ohos/src/main/ets/renderer_native/components/waterfall/HRWaterfall.ets
Signed-off-by: shitijun <shitijun@kaihong.com>
=> add Feature STICKY

framework/ohos/src/main/ets/hippy_framework/adapter/file/FileRequestAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/file/HippyFileAdapter.ets, framework/ohos/src/main/ets/hippy_framework/modules/nativemodules/audio/AudioPlayerModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/nativemodules/deviceevent/DeviceEventModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/nativemodules/exception/ExceptionModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/nativemodules/image/ImageLoaderModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/nativemodules/netinfo/NetInfoModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/nativemodules/network/WebSocketModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/nativemodules/storage/StorageModule.ets
=> add nativeModules about storage、image、audio、exception、etc.

framework/ohos/src/main/ets/renderer_native/components/list/HRListView.ets, framework/ohos/src/main/ets/renderer_native/components/web/HRWebView.ets
=> modify WebView AND fix List bug

framework/ohos/src/main/ets/renderer_native/components/image/HRImageView.ets, framework/ohos/src/main/ets/renderer_native/components/richtext/HRRichTextView.ets
=> feat(ohos): impl of image span attribute

dom/include/dom/yoga_layout_node.h, dom/src/dom/yoga_layout_node.cc, driver/js/CMakeLists.txt, framework/android/src/main/cpp/CMakeLists.txt, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, modules/footstone/src/worker_manager.cc
=> fix issues found when integrating VL

.gitignore, framework/ohos/src/main/cpp/impl/CMakeLists.txt, modules/ohos/oh_napi/include/oh_napi/ark_ts.h, modules/ohos/oh_napi/src/ark_ts.cc
=> modifies for VL

framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc, framework/ohos/src/main/ets/renderer_native/components/richtext/HRRichTextView.ets, modules/ohos/oh_napi/include/oh_napi/oh_measure_text.h, modules/ohos/oh_napi/src/oh_measure_text.cc
=> feat(ohos): fix measure of imageSpan

framework/examples/ohos-demo/src/main/ets/entryability/EntryAbility.ets, framework/examples/ohos-demo/src/main/ets/fonts/TTTGB.otf
=> feat(ohos): add register font

dom/CMakeLists.txt, framework/ohos/index.ets, framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc, framework/ohos/src/main/ets/hippy_framework/HippyEngine.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/index.ets, framework/ohos/src/main/ets/renderer_native/HippyRootView.ets
=> Export some symbols and modifications for VL

modules/vfs/ohos/src/handler/asset_handler.cc
=> Fix crash when loading asset fail

framework/ohos/src/main/ets/hippy_framework/adapter/file/FileRequestAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/DefaultHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpRequest.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HttpTaskCallbackImpl.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/audio/AudioPlayerModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/debug/DevMenuModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/deviceevent/DeviceEventModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/exception/ExceptionModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/image/ImageLoaderModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/netinfo/NetInfoModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/NetworkModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/WebSocketModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/storage/StorageModule.ets
=> Optimize the details

modules/vfs/ohos/CMakeLists.txt, modules/vfs/ohos/include/vfs/Uri.h, modules/vfs/ohos/src/Uri.cc, modules/vfs/ohos/src/handler/asset_handler.cc, modules/vfs/ohos/src/handler/file_handler.cc, modules/vfs/ohos/src/vfs_manager_napi.cc
=> implement file_handler

framework/ohos/build-profile.json5, framework/ohos/src/main/ets/hippy_framework/adapter/executor/DefaultExecutorSupplierAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/executor/HippyExecutorSupplierAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpRequest.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/audio/AudioPlayerModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/console/ConsoleModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/debug/DevMenuModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/deviceevent/DeviceEventModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/exception/ExceptionModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/image/ImageLoaderModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/netinfo/NetInfoModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/NetworkModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/WebSocketModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/storage/StorageModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/utils/UtilsModule.ets, framework/ohos/src/main/ets/support/workers/worker.ets
=> modify adapters and modules

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/native_render_impl_napi.h, framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_impl_napi.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc, framework/ohos/src/main/ets/renderer_native/NativeRenderImpl.ets, framework/ohos/src/main/ets/renderer_native/NativeRenderProvider.ets, framework/ohos/src/main/ets/renderer_native/components/base/HippyRenderBaseView.ets, framework/ohos/src/main/ets/renderer_native/components/richtext/HRRichTextView.ets, modules/ohos/oh_napi/include/oh_napi/oh_measure_text.h, modules/ohos/oh_napi/src/oh_measure_text.cc
=> feat(ohos): use c measure span position

modules/ohos/oh_napi/src/oh_measure_text.cc
=> feat(ohos): fix measure bug

framework/ohos/src/main/ets/hippy_framework/adapter/device/DefaultDeviceAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/device/HippyDeviceAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyResourceLoader.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets, framework/ohos/src/main/ets/support/utils/DimensionsUtil.ets
=> add fileadapter、dimentions logics

framework/examples/ohos-demo/src/main/ets/entryability/EntryAbility.ets, framework/examples/ohos-demo/src/main/resources/resfile/fonts/TTTGB.otf, modules/ohos/oh_napi/include/oh_napi/oh_measure_text.h, modules/ohos/oh_napi/src/oh_measure_text.cc
=> feat(ohos): font path for c measure

framework/ohos/src/main/ets/hippy_framework/adapter/file/FileRequestAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/DefaultHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpRequest.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpResponse.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyResourceLoader.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HttpTaskCallbackImpl.ets, framework/ohos/src/main/ets/renderer_native/components/image/ImageLoader.ets, framework/ohos/src/main/ets/support/utils/DimensionsUtil.ets, framework/ohos/src/main/ets/support/utils/TimeMonitor.ets, framework/ohos/src/main/ets/vfs/ResourceDataHolder.ets
=> add framewk http logics

framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyResourceLoader.ets, framework/ohos/src/main/ets/hippy_framework/index.ets
=> Fix assets load issue

framework/ohos/src/main/ets/hippy_framework/adapter/file/FileRequestAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/file/HippyFileAdapter.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/image/ImageLoaderModule.ets, framework/ohos/src/main/ets/support/utils/DimensionsUtil.ets, framework/ohos/src/main/ets/vfs/ResourceDataHolder.ets
=> Improve network requests logics

framework/ohos/src/main/ets/hippy_framework/adapter/http/DefaultHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpAdapter.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/NetworkModule.ets
=>  modify cookie logics

framework/ohos/src/main/ets/hippy_framework/adapter/device/DefaultDeviceAdapter.ets, framework/ohos/src/main/ets/hippy_framework/adapter/device/HippyDeviceAdapter.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/image/ImageLoaderModule.ets, framework/ohos/src/main/ets/support/utils/DimensionsUtil.ets
=> modify dimension logics

framework/ohos/src/main/ets/hippy_framework/HippyEngine.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeImpl.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManager.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/connector/JsDriver.ets, framework/ohos/src/main/ets/hippy_framework/modules/HippyModuleManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/modules/HippyModulePromise.ets, framework/ohos/src/main/ets/hippy_framework/modules/HippyModulePromiseImpl.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/audio/AudioPlayerModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/console/ConsoleModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/debug/DevMenuModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/deviceevent/DeviceEventModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/exception/ExceptionModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/image/ImageLoaderModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/netinfo/NetInfoModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/NetworkModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/WebSocketModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/storage/StorageModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/utils/UtilsModule.ets
=> feat(ohos): bridge callback

modules/footstone/include/footstone/task_runner.h, modules/footstone/include/footstone/worker.h
=> expose worker to friend classes

framework/ohos/src/main/ets/hippy_framework/adapter/file/FileRequestAdapter.ets, framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/audio/AudioPlayerModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/image/ImageLoaderModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/netinfo/NetInfoModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/network/NetworkModule.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/storage/StorageModule.ets
=> modify network logics

framework/ohos/src/main/ets/hippy_framework/HippyEngineContext.ets, framework/ohos/src/main/ets/hippy_framework/HippyEngineContextImpl.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevExceptionDialog.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevFloatButton.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevRemoteServerData.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevServerCallBack.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevServerConfig.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevServerHelper.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevServerImpl.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevServerInterface.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/DevSupportManager.ets, framework/ohos/src/main/ets/hippy_framework/devsupport/LiveReloadController.ets, framework/ohos/src/main/ets/hippy_framework/modules/native/debug/DevMenuModule.ets
=> add many devsupport logics

framework/examples/ohos-demo/src/main/ets/pages/Index.ets
=> modify file format

framework/ohos/src/main/ets/renderer_native/components/base/HippyRenderBaseView.ets
=> fix: js change the border style not work

framework/ohos/src/main/ets/renderer_native/components/base/HippyRenderBaseView.ets, framework/ohos/src/main/ets/renderer_native/utils/HRConvertUtil.ets
=> fix: fix background-image to support asset:/ resource

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/arkui_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/scroll_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/scroll_view.h, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/arkui_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/scroll_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/scroll_view.cc
=> Arkuic scroll

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/text_area_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/text_input_base_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/text_input_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/text_input_view.h, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/text_area_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/text_input_base_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/text_input_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/text_input_view.cc
=> textinput capi demo ok

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/image_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/image_view.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/utils/hr_url_utils.h, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/image_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/scroll_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/image_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/scroll_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/utils/hr_url_utils.cc
=> feat(ohos):  add HRImageView

framework/ohos/src/main/ets/renderer_native/components/image/HRImageView.ets
=> feat(ohos):  add image draggable default false

framework/ohos/src/main/cpp/impl/renderer/native/CMakeLists.txt
=> feat(ohos):  fix build error

dom/include/dom/layout_node.h, dom/include/dom/root_node.h, dom/include/dom/taitank_layout_node.h, dom/include/dom/yoga_layout_node.h, dom/src/dom/root_node.cc, dom/src/dom/yoga_layout_node.cc, framework/ohos/src/main/ets/renderer_native/components/base/HippyRenderBaseView.ets
=> some modifications for vl

framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/image_node.cc
=> feat(ohos): c api fix image tintColor

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/utils/hr_url_utils.h, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/image_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/image_span_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/image_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/rich_text_image_span_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/utils/hr_url_utils.cc
=> feat(ohos): c api - fix image asset image show

framework/ohos/src/main/cpp/impl/renderer/native/src/components/image_view.cc
=> feat(ohos): c api - image mode fix

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/water_flow_item_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/water_flow_node.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/pull_footer_view.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/waterfall_view.h, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/water_flow_item_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/water_flow_node.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/pull_footer_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/pull_header_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/waterfall_item_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/waterfall_view.cc
=> waterfall ok

framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/image_node.cc
=> feat(ohos): c api - image tint color fix

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/image_view.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/native_render_impl.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/native_render_manager.h, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/uimanager/hr_view_manager.h, framework/ohos/src/main/cpp/impl/renderer/native/src/components/image_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/uimanager/hr_view_manager.cc
=> feat(ohos): add fetch image api

framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc
=> Fix moveNodes for different parent nodes

framework/ohos/src/main/cpp/impl/renderer/native/src/components/base_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/components/image_view.cc, framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc
=> feat(ohos): c api - image add blur and shadow offset change

framework/ohos/src/main/cpp/impl/renderer/native/src/components/base_view.cc
=> feat(ohos): fix view linearGradient angle support negative number

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/uimanager/hr_view_manager.h, framework/ohos/src/main/cpp/impl/renderer/native/src/uimanager/hr_view_manager.cc, framework/ohos/src/main/ets/renderer_native/NativeRenderProvider.ets
=> feat(ohos): add fp fcp

framework/ohos/src/main/cpp/impl/renderer/native/src/utils/hr_convert_utils.cc
=> feat(ohos):  fix animation translate & scale

dom/src/dom/animation/cubic_bezier_animation.cc, framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/utils/hr_value_utils.h
=> feat(ohos):  fix animation background color

docs/development/native-module.md, framework/ohos/src/main/cpp/impl/connector/include/connector/arkts_turbo_module.h, framework/ohos/src/main/cpp/impl/connector/src/arkts_turbo_module.cc, framework/ohos/src/main/ets/hippy_framework/modules/HippyModuleManagerImpl.ets, modules/ohos/oh_napi/include/oh_napi/ark_ts.h, modules/ohos/oh_napi/include/oh_napi/oh_napi_object.h, modules/ohos/oh_napi/src/ark_ts.cc, modules/ohos/oh_napi/src/oh_napi_object.cc
=> feat(ohos): update jsi doc && fix null pointer

framework/ohos/src/main/ets/renderer_native/components/richtext/HRRichTextView.ets
=> fix: remove unsupported attribute(breaks IDE 5.0.5.310)

framework/ohos/src/main/cpp/impl/connector/include/connector/arkts_turbo_module.h, framework/ohos/src/main/cpp/impl/connector/src/arkts_turbo_module.cc, framework/ohos/src/main/cpp/impl/connector/src/turbo_module_manager.cc
=> fix(ohos): fix turbo crash
